export default [
    require('./src/exits/static'),
    require('./src/exits/dynamic'),
    require('./src/editors/form'),
    require('./src/inputs/code'),
    require('./src/editors/code'),
    require('./src/inputs/collapsible_group'),
    require('./src/editors/collapsible_group'),
    require('./src/inputs/data_out'),
    require('./src/editors/data_out'),
    require('./src/editors/divider'),
    require('./src/inputs/divider'),
    require('./src/inputs/dynamic_exits'),
    require('./src/editors/dynamic_exits'),
    require('./src/inputs/exits/label'),
    require('./src/inputs/exits/dynamic'),
    require('./src/inputs/exits/static'),
    require('./src/editors/exits/label'),
    require('./src/inputs/header'),
    require('./src/editors/header'),
    require('./src/inputs/list'),
    require('./src/editors/list'),
    require('./src/inputs/select'),
    require('./src/editors/select'),
    require('./src/editors/switch'),
    require('./src/inputs/switch'),
    require('./src/editors/text_message'),
    require('./src/inputs/text_message'),
    require('./src/editors/text_reprompt'),
    require('./src/inputs/text_reprompt'),
    require('./src/inputs/textbox'),
    require('./src/editors/textbox'),
    require('./src/inputs/voice_reprompt'),
    require('./src/editors/voice_reprompt'),
    require('./src/inputs/wildcard'),
    require('./src/editors/wildcard')
    // // require('./src/luis/wrapper')
];

export const meta = {
    name    : 'or-ui-components',
    type    : 'onereach-studio-plugin',
    label   : 'Default components',
    version : '1.0'
};
